version: 2.1
orbs:
  codecov: codecov/codecov@3
  browser-tools: circleci/browser-tools@1.2.3

jobs:
  build:
    working_directory: ~/unit-test
    docker:
      - image: cimg/node:current-browsers
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - checkout
      # Restore local dependencies from cache
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      # Cache local dependencies if they don't exist
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
              - node_modules
      - run:
          name: Run tests and collect coverage
          command: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - codecov/upload

workflow:
  version: 2.1
  build-test:
    jobs:
      - build