version: 2.1
orbs:
  codecov: codecov/codecov@3

jobs:
  build:
    docker:
      - image: cimg/node:current-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests and collect coverage
          command: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - codecov/upload

workflow:
  version: 2.1
  build-test:
    jobs:
      - build